CREATE TABLE IF NOT EXISTS ODONTOLOGOS (ID INT AUTO_INCREMENT PRIMARY KEY,
   APELLIDO VARCHAR(50),
   NOMBRE VARCHAR(50),
   MATRICULA VARCHAR(50));

CREATE TABLE IF NOT EXISTS PACIENTES (ID INT AUTO_INCREMENT PRIMARY KEY,
   APELLIDO VARCHAR(50),
   NOMBRE VARCHAR(50),
   DNI VARCHAR(25),
   DOMICILIO VARCHAR(100),
   ALTA DATE);

CREATE TABLE IF NOT EXISTS TURNOS (
    ID int AUTO_INCREMENT,
    ODONTOLOGOID int NOT NULL,
    PACIENTEID int NOT NULL,
    FECHA TIMESTAMP,
    PRIMARY KEY (ID),
    FOREIGN KEY (ODONTOLOGOID) REFERENCES ODONTOLOGOS(ID),
    FOREIGN KEY (PACIENTEID) REFERENCES PACIENTES(ID)

);